version: "3.7"
services:
  app:
    build:
      args:
        user: bypabloc
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: good_meal
    container_name: good_meal-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - good_meal

  # db:
  #   image: mysql:5.7
  #   container_name: good_meal-db
  #   restart: always
  #   # restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  #   networks:
  #     - good_meal
    #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 8889:3306
    environment:
      MYSQL_DATABASE: good_meal
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - good_meal

  nginx:
    image: nginx:alpine
    container_name: good_meal-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - good_meal

networks:
  good_meal:
    driver: bridge
